### ISSUE TITLE
Mismatch on UK Large configuration

### ISSUE THREAD

**Issue by pcolmer** [Linaro/cloud#11]
The website says that a UK Large instance is 24 vCPU and 30GB memory. Both China and USA say 8vCPU and 60GB memory, and this is what is on PayWhirl on the UK Projects page.

**Comment by kylekirkby** [comment]
Thanks @pcolmer - I'm sending an email to Jorge/Martin now to get an accurate official pricing list.

**Comment by kylekirkby** [comment]
Closing this due to new goals for the Developer Cloud Project.
